apiVersion: apps/v1
kind: Deployment
metadata:
  name: nodejs-mongodb-service
  labels:
    app: nodejs-mongodb-service
spec:
  selector:
    matchLabels:
      app: nodejs-mongodb-service
  template:
    metadata:
      labels:
        app: nodejs-mongodb-service
    spec:
      containers:
      - name: nodejs-mongodb-service
        image: bobcrutchley/nodejs-mongodb-service:latest
        ports:
        - name: http-port
          containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: nodejs-mongodb-service
spec:
  type: ClusterIP
  ports:
  - port: 3000
  selector:
    app: nodejs-mongodb-service

